In [12]:
####https://scikit-learn.org/stable/modules/preprocessing_targets.html
####备注：这里的数据转化只针对目标数据
from sklearn import preprocessing

In [14]:
####方法一：二进制化
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelBinarizer.html#sklearn.preprocessing.LabelBinarizer
lb = preprocessing.LabelBinarizer()
target=['yes', 'no', 'no', 'yes']
lb.fit_transform(target)

array([[1],
       [0],
       [0],
       [1]])

In [15]:
target=[1, 2, 6, 4, 2]######这个时候目标值中的组成是1，2，4，6四个数值，因此可以用4维向量组成
lb.fit_transform(target)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0]])

In [16]:
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder
######方法二：除了进行0，1这种转化外还可以实现0到n-1的编码转化
le= preprocessing.LabelEncoder()
target=[1, 2, 6, 4, 2]############目标数据中是1，2，4，6四种类型数据，可以实现0-3的编码转化
le.fit(target)
le.transform(target)

array([0, 1, 3, 2, 1])

In [25]:
#https://scikit-learn.org/stable/modules/generated/sklearn.compose.TransformedTargetRegressor.html
###方法三：QuantileTransformer
#####其它转换：https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.QuantileTransformer.html#sklearn.preprocessing.QuantileTransformer
import numpy as np
from sklearn.datasets import load_boston
from sklearn.compose import TransformedTargetRegressor
from sklearn.preprocessing import QuantileTransformer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
boston = load_boston()
X = boston.data
y = boston.target

###########################转换之前的相关系数
regressor = LinearRegression()
raw= regressor.fit(X, y)
print(raw.score(X, y))
###########################转换之后的相关系数
transformer = QuantileTransformer(output_distribution='normal')
regr = TransformedTargetRegressor(regressor=regressor,transformer=transformer)
after=regr.fit(X, y) 
print(after.score(X,y))

0.7406426641094094
0.7111568262433855


In [1]:
#####方法四：power_transform目前只支持 Box-Cox transform and the Yeo-Johnson transform两种
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.power_transform.html#sklearn.preprocessing.power_transform
import numpy as np
from sklearn.preprocessing import power_transform
data = [[1, 2], [3, 2], [4, 5]]
print(power_transform(data, method='box-cox'))  ###yeo-johnson or box-cox

[[-1.33269291 -0.70710678]
 [ 0.25653283 -0.70710678]
 [ 1.07616008  1.41421356]]


In [ ]:
#######备注：对于target数据转化前后的影响可以参考如下链接：
########https://scikit-learn.org/stable/auto_examples/compose/plot_transformed_target.html#sphx-glr-auto-examples-compose-plot-transformed-target-py